---
- name: testing router commands
  gather_facts: false
  connection: network_cli
  vars_files:
   - vars/main.yml
  hosts: asr9k

  roles:
   - role: asr9k


  tasks:
    - name: connection and show interface commands
      ios_command:
        commands: show ip int br
      register: output
    - name: Display
      debug:
        msg: "{{output.stdout_lines}}"
