---
- name: testing router commands
  hosts: asr9k
  gather_facts: no
  connection: network_cli
  vars:
    ansible_user: username
    ansible_password: password
    ansible_network_os: iosxr

  tasks:
    - name: connection and show interface commands
      iosxr_command:
        commands: show ip int br
      register: output
    - name: Display
      debug:
        msg: "{{output.stdout_lines}}"
